version: "3.7"

services:
  waitfordb:
        image: dadarek/wait-for-dependencies
        depends_on:
            mysql:
              condition: service_completed_successfully
        environment:
            MYSQL_PORT: "5432"
        networks:
            - backend
        command: mysql:5432
  mysql:
    image: mysql:5.7
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: flaskmysql
  web:
    build: .
    depends_on:
      mysql:
        condition: service_completed_successfully
      waitfordb:
        condition: service_completed_successfully
    ports:
      - 5000:5000
    
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: "12345678"
      MYSQL_DB: flaskmysql
  
networks:
    backend:
        driver: bridge
