version: "3.7"

services:
  waitfordb:
        image: dadarek/wait-for-dependencies
        depends_on:
            mysql:
              condition: service_healthy
        environment:
            MYSQL_PORT: "3306"
        command: mysql:3306
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: flaskmysql
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT count(*) FROM information_schema.tables' $$MYSQL_DATABASE"
      interval: 1s
      timeout: 3s
      retries: 20
  web:
    build: .
    depends_on:
      waitfordb:
        condition: service_completed_successfully
    ports:
      - 5000:5000
    command: >
      gunicorn -b 0.0.0.0:5000
        --timeout 120
        --access-logfile -
        --reload
        "user.app:create_app()
    #command: /flask/app/server.py

    
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    volumes:
      - ./:/flask
volumes:
  mysql-data:
